# Generated by Django 3.0.5 on 2021-09-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210831_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden en la barra de navegación'),
        ),
        migrations.AlterField(
            model_name='page',
            name='visible',
            field=models.BooleanField(verbose_name='¿Visible en la página?'),
        ),
    ]
